-- Table : workers (Artisans)
CREATE TABLE IF NOT EXISTS public.workers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    password TEXT NOT NULL,
    phone TEXT NOT NULL,
    job TEXT NOT NULL,
    zone TEXT NOT NULL,
    latitude TEXT,
    longitude TEXT,
    description TEXT,
    "audioDescription" TEXT,
    "profilePhoto" TEXT,
    plan TEXT NOT NULL,
    price INTEGER NOT NULL,
    status TEXT DEFAULT 'Actif',
    date TEXT NOT NULL,
    "paymentMethod" TEXT
);

-- Table : users (Clients)
CREATE TABLE IF NOT EXISTS public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    phone TEXT NOT NULL,
    password TEXT NOT NULL,
    role TEXT DEFAULT 'Client',
    status TEXT DEFAULT 'Actif',
    "dateJoined" TEXT NOT NULL
);

-- Table : reviews (Avis sur les artisans)
CREATE TABLE IF NOT EXISTS public.reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "workerId" BIGINT NOT NULL,
    "clientName" TEXT NOT NULL,
    rating INTEGER NOT NULL,
    comment TEXT NOT NULL,
    date TEXT NOT NULL
);
